version: "3.7"
services:
  app:
    container_name: rw_web
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: "laravelapp"
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  db:
    container_name: rw_db
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    command: --sql_mode=""
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:
